cursor            #fcb0d7
cursor_text_color #511d3d

foreground            #fcb0d7
background            #181115
selection_foreground  #402a35
selection_background  #dfbdcc
url_color             #dfbdcc

#: black 000000 767676
color0  #181115
color8  #181115
#: red cc0403 f2201f
color1  #ffadb3
color9  #ffadb3
#: green 19cb00 23fd00
color2  #b9ffab
color10 #b9ffab
#: yellow cecb00 fffd00
color3  #fff1ab
color11 #fff1ab
#: blue 0d73cc 1a8fff
color4  #badfff
color12 #badfff
#: magenta cb1ed1 fd28ff
color5  #ef9eff
color13 #ef9eff
#: cyan 0dcdcd 14ffff
color6  #adfffb
color14 #adfffb
#: white dddddd ffffff
color7  #ffffff
color15 #ffffff

mark1_foreground #380727
mark1_background #ffd8e9
mark2_foreground #291520
mark2_background #fcd9e8
mark3_foreground #311302
mark3_background #ffdbc9

active_tab_foreground #511d3d
active_tab_background #fcb0d7
inactive_tab_foreground #ffd8e9
inactive_tab_background #6c3454

active_border_color #fcb0d7
inactive_border_color #511d3d
# bell_border_color #ff5a00