cursor            #faba73
cursor_text_color #482900

foreground            #faba73
background            #18120c
selection_foreground  #402d17
selection_background  #e0c1a3
url_color             #e0c1a3

#: black 000000 767676
color0  #18120c
color8  #18120c
#: red cc0403 f2201f
color1  #ffadb3
color9  #ffadb3
#: green 19cb00 23fd00
color2  #b9ffab
color10 #b9ffab
#: yellow cecb00 fffd00
color3  #fff1ab
color11 #fff1ab
#: blue 0d73cc 1a8fff
color4  #badfff
color12 #badfff
#: magenta cb1ed1 fd28ff
color5  #ef9eff
color13 #ef9eff
#: cyan 0dcdcd 14ffff
color6  #adfffb
color14 #adfffb
#: white dddddd ffffff
color7  #ffffff
color15 #ffffff

mark1_foreground #2b1700
mark1_background #ffddbb
mark2_foreground #281805
mark2_background #fdddbd
mark3_foreground #141f01
mark3_background #d9e9b6

active_tab_foreground #482900
active_tab_background #faba73
inactive_tab_foreground #ffddbb
inactive_tab_background #673d00

active_border_color #faba73
inactive_border_color #482900
# bell_border_color #ff5a00