cursor            #b2c5ff
cursor_text_color #182e60

foreground            #b2c5ff
background            #121318
selection_foreground  #2a3042
selection_background  #c0c6dd
url_color             #c0c6dd

#: black 000000 767676
color0  #121318
color8  #121318
#: red cc0403 f2201f
color1  #ffadb3
color9  #ffadb3
#: green 19cb00 23fd00
color2  #b9ffab
color10 #b9ffab
#: yellow cecb00 fffd00
color3  #fff1ab
color11 #fff1ab
#: blue 0d73cc 1a8fff
color4  #badfff
color12 #badfff
#: magenta cb1ed1 fd28ff
color5  #ef9eff
color13 #ef9eff
#: cyan 0dcdcd 14ffff
color6  #adfffb
color14 #adfffb
#: white dddddd ffffff
color7  #ffffff
color15 #ffffff

mark1_foreground #001848
mark1_background #dae2ff
mark2_foreground #151b2c
mark2_background #dce2f9
mark3_foreground #2b122b
mark3_background #fed6f9

active_tab_foreground #182e60
active_tab_background #b2c5ff
inactive_tab_foreground #dae2ff
inactive_tab_background #314578

active_border_color #b2c5ff
inactive_border_color #182e60
# bell_border_color #ff5a00