exec-once = hypridle

# status bar
exec-once = waybar

# wallpaper manager
exec-once = awww-daemon

# notification manager
exec-once = mako

# swayosd server
exec-once = swayosd-server

# wifi + bluetooth daemon
exec-once = wifi-manager
