# Autostart commands alphabetically

# clipboard
exec-once = wl-paste --watch cliphist store

# hypridle
exec-once = hypridle

# notification manager
exec-once = mako

# status bar
exec-once = waybar

# swayosd server
exec-once = swayosd-server

# wallpaper manager
exec-once = awww-daemon

# wifi + bluetooth daemon
exec-once = wifi-manager


