# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#eddfe3"

# Title color for boxes
theme[title]="#fcb0d7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#dfbdcc"

# Background color of selected item in processes box
theme[selected_bg]="#fcb0d7"

# Foreground color of selected item in processes box
theme[selected_fg]="#511d3d"

# Color of inactive/disabled text
theme[inactive_fg]="#d4c2c8"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f3ba9b"

# Cpu box outline color
theme[cpu_box]="#9c8d93"

# Memory/disks box outline color
theme[mem_box]="#9c8d93"

# Net up/down box outline color
theme[net_box]="#9c8d93"

# Processes box outline color
theme[proc_box]="#9c8d93"

# Box divider line and small boxes line color
theme[div_line]="#504349"

# Temperature graph colors
theme[temp_start]="#dfbdcc"
theme[temp_mid]="#fcb0d7"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#dfbdcc"
theme[cpu_mid]="#fcb0d7"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#dfbdcc"
theme[free_mid]=""
theme[free_end]="#58404c"

# Mem/Disk cached meter
theme[cached_start]="#f3ba9b"
theme[cached_mid]=""
theme[cached_end]="#643d26"

# Mem/Disk available meter
theme[available_start]="#fcb0d7"
theme[available_mid]=""
theme[available_end]="#6c3454"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#dfbdcc"
theme[download_mid]="#fcb0d7"
theme[download_end]="#f3ba9b"

# Upload graph colors
theme[upload_start]="#dfbdcc"
theme[upload_mid]="#fcb0d7"
theme[upload_end]="#f3ba9b"