cursor            {{ colors.primary.dark.hex }}
cursor_text_color {{ colors.on_primary.dark.hex }}

foreground            {{ colors.primary.dark.hex }}
background            {{ colors.background.dark.hex }}
selection_foreground  {{ colors.on_secondary.dark.hex }}
selection_background  {{ colors.secondary.dark.hex }}
url_color             {{ colors.secondary.dark.hex }}

#: black 000000 767676
color0  {{ colors.background.dark.hex }}
color8  {{ colors.background.dark.hex }}
#: red cc0403 f2201f
color1  #ffadb3
color9  #ffadb3
#: green 19cb00 23fd00
color2  #b9ffab
color10 #b9ffab
#: yellow cecb00 fffd00
color3  #fff1ab
color11 #fff1ab
#: blue 0d73cc 1a8fff
color4  #badfff
color12 #badfff
#: magenta cb1ed1 fd28ff
color5  #ef9eff
color13 #ef9eff
#: cyan 0dcdcd 14ffff
color6  #adfffb
color14 #adfffb
#: white dddddd ffffff
color7  #ffffff
color15 #ffffff

mark1_foreground {{ colors.on_primary_fixed.dark.hex }}
mark1_background {{ colors.primary_fixed.dark.hex }}
mark2_foreground {{ colors.on_secondary_fixed.dark.hex }}
mark2_background {{ colors.secondary_fixed.dark.hex }}
mark3_foreground {{ colors.on_tertiary_fixed.dark.hex }}
mark3_background {{ colors.tertiary_fixed.dark.hex }}

active_tab_foreground {{ colors.on_primary.dark.hex }}
active_tab_background {{ colors.primary.dark.hex }}
inactive_tab_foreground {{ colors.on_primary_container.dark.hex }}
inactive_tab_background {{ colors.primary_container.dark.hex }}

active_border_color {{ colors.primary.dark.hex }}
inactive_border_color {{ colors.on_primary.dark.hex }}
# bell_border_color #ff5a00